### ISSUE TITLE
Conection fail (SSL Ciphers needs)

### ISSUE THREAD

**Issue by hamster66** [J-Rios/uTLGBotLib-arduino#1]
Hi.
I try your example (echo) on ESP8266 (Arduino) and a have only
```
[Bot] Connecting to telegram server...
[Bot] Conection fail.
[Bot] Connecting to telegram server...
[Bot] Conection fail.

```
What needs to be done to make the example work?

**Comment by hamster66** [comment]
Ok. It works if compile with **All SSL chipers** options.

**Comment by J-Rios** [comment]
Also remember that you can increase debug level when connection fail to point out what is the cause of the problem by define:

// Enable Bot debug level (0 - None; 1 - Bot Level; 2 - Bot+HTTPS Level)
#define DEBUG_LEVEL_UTLGBOT 2

Regards.
